import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'
import { cn } from "@/lib/utils";
import WalletLayout from "@/context/WalletLayout";
import { Toaster } from "@/components/ui/toaster"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MAGIK Presale Page",
  description: "Generated by create next app",
};
const deacon = localFont({
  src: [
    {
      path: '../../public/fonts/Aclonica-Regular.ttf',
      weight: '800',
    },
  ],
  variable: '--font-deacon',
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    
    
    <html lang="en">
        <body className={cn(
          inter.className, deacon.variable

        )}>
        <WalletLayout>

          {children}
          <Toaster />
    </WalletLayout>
          </body>
      </html>
  );
}
